### ISSUE TITLE
ubuntu16环境下编译测试，同样用simple测试程序，客户端无法连接到服务端。

### ISSUE THREAD

**Issue by angryant198512** [caozhiyi/CppNet#10]
![image](https://user-images.githubusercontent.com/49151858/123041700-3f41f680-d428-11eb-9075-1053944907c0.png)
ubuntu16环境下编译测试，同样用simple测试程序，客户端无法连接到服务端。windows正常。

_Originally posted by @angryant198512 in https://github.com/caozhiyi/CppNet/issues/9#issuecomment-866544615_

**Comment by caozhiyi** [comment]
是因为创建socket的时候没有检查是IPv6还是IPv4，导致创建了IPv6的socket去bind IPv4的地址。
已经修复，非常感谢！！
