### ISSUE TITLE
simple下client的close无法被server捕捉到

### ISSUE THREAD

**Issue by duckYcy** [caozhiyi/CppNet#14]
![image](https://user-images.githubusercontent.com/50080225/144708428-c8b6c4f7-d6a8-4810-9fef-d6f20f626ca5.png)
请问是什么原因呢

**Comment by duckYcy** [comment]
将server中ReadFunc下的输出全部注释掉，就不会有这个问题了😂😂😂

**Comment by caozhiyi** [comment]
linux平台上client 的 close，server 端会通过检测socket read返回0捕获断开事件。windows上 wepoll 不会返回 EPOLLIN 而是直接返回EPOLLHUP，在事件处理函数中没有处理 EPOLLHUP 导致捕获不到断开事件。已经在关联的提交中修改。  
感谢关注！感谢本issue。
