### ISSUE TITLE
请问该如何处理这个 EPOLLHUP 事件？

### ISSUE THREAD

**Issue by ywwyewenwei** [caozhiyi/CppNet#15]
作者您好！非常欣赏您开源的这份代码。
       一、在我的学习过程中，发现有如下现象：
 
        1、下载并编译代码，运行其中的 echo_server.exe 程序；
        2、运行windows的任务管理器--->性能----->打开资源监视器，发现echo_server.exe进程的cpu 使用率为0，正常；
        3、运行echo_client.exe，等到在echo_client.exe窗口中能看到数据从服务器返回后，关闭echo_client.exe；
        4、在资源监视器中发现，echo_server.exe进程cpu占用率异常高，50%以上。

      二、我的环境：
        1、windows 11；
             
![e52eedfa07236bfba94641cc76d6de8](https://user-images.githubusercontent.com/46886131/145211051-2d3f9ca0-c55b-4954-9740-f6bdc7648c78.png)
        2、编译工具：Visual studio 2022。

     三、跟踪代码的发现：
        1、在epoll_action.cpp的EpollEventActions::ProcessEvent() 函数中，
              每次循环都能得到一个 EPOLLHUP 事件；

        2、在接下来的epoll_action.cpp文件的第290行：
              OnEvent(_active_list, ret); 
             这里并没有对EPOLLHUP 事件进行任何处理，从而使得系统进入一个无限循环当中。

            请教：这里该如何处理为好？
                                                                                                            谢谢！

**Comment by caozhiyi** [comment]
linux平台上client 的 close，server段会通过检测socket read返回0捕获断开事件。windows上epoll不会返回 EPOLLIN 而是直接返回EPOLLHUP，没有处理EPOLLHUP导致陷入死循环。  
这次提交在事件处理中检测了EPOLLHUP标识，将断开连接的socket从wepoll里删除掉就可以了。   
最后，感谢关注！感谢本issue。
阿门。
