### ISSUE TITLE
httpser: segmentation fault 以及 free(): corrupted unsorted chunks 错误

### ISSUE THREAD

**Issue by rzbdz** [caozhiyi/CppNet#19]
你好，我通过项目的 CMakeLists 编译了 test/http 下的 httpser 示例程序，然后通过 wget 访问一个页面，wget 单个可以下载成功，但是使用 apache benchmark 测试的时候：

```
ab -n 10000 -c 1 http://127.0.0.1:8921/hello
```
可以成功测试，
```
ab -n 10000 -c 2 http://127.0.0.1:8921/hello
```
会出现
```
[1]    21053 segmentation fault  sudo ./httpser
```
错误，然后 -c 为 2 ~ 13 都是出现 segmentation fault 错误，
-c 14 以后会出现
```
free(): corrupted unsorted chunks
[1]    21455 abort      ./httpser
```
-c 20 以后会出现
```
free(): corrupted unsorted chunks
free(): corrupted unsorted chunks
[1]    21359 abort      ./httpser
```
的错误，请问我应该如何找到错误提供更多的信息 ？

编译器是 g++-11, x64 Ubuntu 20.04

**Comment by caozhiyi** [comment]
我调试了一下，当ab 测试不使用 -k 参数时，每次请求均为短连接，所以在
`
void HttpServer::OnRequest(cppnet::Handle handle, bool close, const HttpRequest& req) {
    HttpResponse response(close);
    _http_call_back(req, response);

    std::string res = response.GetSendBuffer();
    handle->Write(res.c_str(), (uint32_t)res.length());
    if (response.GetCloseConnection()) {
        handle->Close();
    }
}
`
中会断开连接，而断开连接则触发
`
void HttpServer::OnDisConnection(cppnet::Handle handle, uint32_t err) {
    auto context = (HttpContext*)handle->GetContext();
    delete context;
}
`
会析构掉 context。
而在OnMessage 函数中，没有判断是否会断开连接接着调用
`
context->Reset();
`
而context已经在上述的OnDisConnection析构掉，由此导致此问题。
