### ISSUE TITLE
Linux编译报错，存在两处函数未正确引用

### ISSUE THREAD

**Issue by wdir** [caozhiyi/CppNet#2]
**第一处错误 bind函数未定义：

> **
> In file included from base/RunnableAloneTaskList.h:4,
>                  from base/Log.h:7,
>                  from base/Log.cpp:3:
> base/Runnable.h: In member function ‘virtual void base::CRunnable::Start()’:
> base/Runnable.h:18:78: error: ‘bind’ is not a member of ‘std’
>    18 | _pthread = std::shared_ptr<std::thread>(new std::thread(std::bind(&CRunnable::Run, this)));

_解决措施：_
        找到源代码 /base/Runnalbe.h,在第4行增加 “#include <functional>”

**第二处问题readv writev函数未定义
> **
> e::CMemSharePtr<cppnet::CEventHandler>&)’:
> net/linux/SocketImpl.cpp:155:28: error: ‘readv’ was not declared in this scope; did you mean ‘read’?
>   155 |                 recv_len = readv(socket_ptr->GetSocket(), (iovec*)&*io_vec.begin(), io_vec.size());
>       |                            ^~~~~
>       |                            read
> net/linux/SocketImpl.cpp: In member function ‘void cppnet::CSocketImpl::Send(base::CMemSharePtr<cppnet::CEventHandler>&)’:
> net/linux/SocketImpl.cpp:208:23: error: ‘writev’ was not declared in this scope; did you mean ‘write’?
>   208 |             int res = writev(socket_ptr->GetSocket(), (iovec*)&*io_vec.begin(), io_vec.size());
>       |                       ^~~~~~
> 

_解决措施：_
         源代码中 /net/linux/SocketImpl.cpp第5行增加“#include <sys/uio.h>”

**Comment by caozhiyi** [comment]
感谢提出本issue, 我已经按照建议在相关文件处添加了头文件引用。
该问题可能是Linux版本不同所致，因为我之前的编译都没有报错，甚至travis-ci也没报错，但添加了头文件的引用还是比较保险。
再次感谢！

**Comment by wdir** [comment]
ok!
