### ISSUE TITLE
内存分配PoolAlloter

### ISSUE THREAD

**Issue by 271812697** [caozhiyi/CppNet#20]
void* PoolAlloter::ChunkAlloc(uint32_t size, uint32_t& nums) {
    //
   //
    //suspicion
    if (left_bytes > 0) {
        MemNode* my_free = _free_list[FreeListIndex(left_bytes)];
        ((MemNode*)_pool_start)->_next = my_free;
        _free_list[FreeListIndex(size)] = (MemNode*)_pool_start;
    }

}

**Comment by 271812697** [comment]
这里是不是写错了

**Comment by caozhiyi** [comment]
这里是为了尽量利用所有内存，当剩余的内存大小不足以满足当前申请的时候，就把剩余的内存放到内存管理结果对应的链表中，然后再申请新的内存。

**Comment by 271812697** [comment]
我后来看懂了，返还到链表的内存大小刚好是最小对齐的整数倍，我之前一直疑惑这个
