### ISSUE TITLE
粘包问题

### ISSUE THREAD

**Issue by yoovor** [caozhiyi/CppNet#23]
请问怎么解决粘包问题的呢

**Comment by caozhiyi** [comment]
这是个tcp网络库，上层接口读出来的数据其实还是字节流，并没有处理粘包问题。
应用层协议处理粘包的手段，可以参考下http的实现，其实一般也就这两种方式：
1. 在传输的数据里添加特殊字符表示结束，比如http头结束标识 /r/n
2. 协议头中明确协议体长度，比如http的header 的 content length 属性
第二个方案中怎么解析协议头？
也是相似的原理：
1. 固定协议头长度，比如每个数据包前四自己固定是长度信息
2. 特殊标识，还是类似http的 /r/n
