### ISSUE TITLE
Connect()方法能否返回Handle

### ISSUE THREAD

**Issue by pzhu1015** [caozhiyi/CppNet#31]
如果我多个对象高并发，发起连接后OnConnect我无法与我的对象绑定, 有什么办法可以解决吗

**Comment by caozhiyi** [comment]
你的使用场景是什么？因为所有的接口都是异步的，所以没办法在函数中立即返回建链的handler。
一般而言，Connection接口在client侧发起调用，然后才会用到connection call back, 而client侧需要并发多个tcp的情况也比较少见。你可以将要绑定的资源创建动作放在链接建立后，换下资源的建立时机

**Comment by pzhu1015** [comment]
我是全局共用的一个cppnet io, 因为我是连接上游通道，多个通道可能连接的是同一个ip + port,每个通道有可能发起多个连接, 连接回调时我无法知道是谁发起的连接

**Comment by caozhiyi** [comment]
还是没太理解你的场景，client 需要和 server 建立多个tcp连接？
为什么要在连接建立前，给连接关联上下文呢？
可以加我微信 详细了解下设计
