### ISSUE TITLE
master 分支EpollEventActions 析构函数编译错误

### ISSUE THREAD

**Issue by YOCEAN** [caozhiyi/CppNet#32]
./CppNet-master/cppnet/event/epoll/epoll_action.cpp: In destructor ‘virtual cppnet::EpollEventActions::~EpollEventActions()’:
.CppNet-master/cppnet/event/epoll/epoll_action.cpp:53:27: error: invalid operands of types ‘int32_t {aka int}’ and ‘std::nullptr_t’ to binary ‘operator!=’
     if (_epoll_handler != nullptr)

**Comment by YOCEAN** [comment]
EpollEventActions::~EpollEventActions() {
#ifdef __win__
        if (_epoll_handler != nullptr) {
#else
        if (_epoll_handler != -1) {
#endif

#ifdef __win__
        epoll_close(_epoll_handler);
#else
        close(_epoll_handler);
#endif
    }
}
看起来，这样就好了

**Comment by caozhiyi** [comment]
你在什么平台上编译的？

**Comment by YOCEAN** [comment]
centos

**Comment by caozhiyi** [comment]
你可以提交个merge
