### ISSUE TITLE
connect连接一个不存在地址，ubuntu 下会报成功 ，windows 下面会报失败

### ISSUE THREAD

**Issue by yflisa** [caozhiyi/CppNet#39]
![image](https://github.com/user-attachments/assets/868db5dc-f847-4d56-9b3f-45fce260cc92)

**Comment by yflisa** [comment]
> <img alt="1726839080449" width="960" src="https://private-user-images.githubusercontent.com/22977396/369424124-8ed8b68b-9173-4388-9601-564d4f07446c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mzk1MjQsIm5iZiI6MTcyNjgzOTIyNCwicGF0aCI6Ii8yMjk3NzM5Ni8zNjk0MjQxMjQtOGVkOGI2OGItOTE3My00Mzg4LTk2MDEtNTY0ZDRmMDc0NDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzMzM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNzM3ODVjNWZmNzdjMTE2MDFlOTI1OWMxMmZjYjAxZWM3YWQ2ODBmOTJmMGE1MmYwNmIxMTM2YmQzZTg1NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.47C7TQOCiNqMrx8AQ2A0pOZ0BQM7A2jG1uIIxoUBtzs"> <img alt="connect_error" width="960" src="https://private-user-images.githubusercontent.com/22977396/369424298-ed212c22-e873-46b4-996b-d8a462875157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4Mzk1MjQsIm5iZiI6MTcyNjgzOTIyNCwicGF0aCI6Ii8yMjk3NzM5Ni8zNjk0MjQyOTgtZWQyMTJjMjItZTg3My00NmI0LTk5NmItZDhhNDYyODc1MTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzMzM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NDJhMDM4MDgyNGQ2NWQ0MWQ1YmQxMmU1MTUyNjU5ZmQ1YjgzNGJhZTEyYTE1ZDk4NzhlMGJhNTRlYzRlZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OKusUMSrN86LEaAyPcHRoSJkFzRqezdsGYVhYVrnCxE">

**Comment by caozhiyi** [comment]
![sample](https://github.com/user-attachments/assets/44beb172-4727-44d9-bba0-bc2a41c78a8b)
我在测试中无法复现，你可以debug下吗？关键看下这里：
common/network/posix/socket.cpp
```
bool CheckConnect(const uint64_t sock) {
    int32_t ret = 0;
    socklen_t len = sizeof(ret);
    if (getsockopt(sock, SOL_SOCKET, SO_ERROR, &ret, &len) == -1) {
        return false;
    }
    if(ret != 0) {
        return false;
    }
    return true;
}
```
因为所有的io操作都是异步的，connect非阻塞立即返回，如果当下无法判断是否连接成功，会有个定时器来通过上述的函数来监测连接状态。

**Comment by yflisa** [comment]
您好，common/network/posix/socket.cpp 函数修改成下面这样可以，请您看下是否可以

```
bool CheckConnect(const uint64_t sock) {
	int ret = 0;
	int loop = 0;
	int err_ret=0;  
	socklen_t len;
	int epoll_cnt = 0;
	int epoll_event = 0;

	struct epoll_event epoll_event_arr[1]; 
	struct epoll_event epoll_event_ev;
	struct epoll_event t_epoll_event;  

	int fd = sock;  
	int epoll_fd = epoll_create(1); 
	if (-1 == epoll_fd)
	{
		return false;
	}

	memset(&t_epoll_event, 0, sizeof(t_epoll_event));
	t_epoll_event.events = (EPOLLIN | EPOLLOUT | EPOLLET);
	t_epoll_event.data.u64 = (int)fd;  
	if (0 != epoll_ctl(epoll_fd, EPOLL_CTL_ADD, fd, &t_epoll_event))
	{
		close(epoll_fd);
		return false;
	}

	len = sizeof(err_ret);  
	epoll_cnt = epoll_wait(epoll_fd, epoll_event_arr, 1, 5000);
	if (epoll_cnt < 0)
	{
		//error
		close(epoll_fd);
		epoll_fd = -1;
        LOG_ERROR("epoll_wait < 0, fd:%d",fd);
		return false;
	}
	else if (0 == epoll_cnt)
	{
		//timeout
		close(epoll_fd);
		epoll_fd = -1;
        LOG_ERROR("epoll_wait = 0, fd:%d",fd);
		return false;
	}

	for (loop = 0; loop < epoll_cnt; loop++) 
	{  
		epoll_event_ev = epoll_event_arr[loop];  
		epoll_event = epoll_event_ev.events;  
		if (epoll_event & EPOLLERR) 
		{  
			close(epoll_fd);
			epoll_fd = -1;
            LOG_ERROR("epoll_wait EPOLLERR fd:%d",fd);
			return false;

		}  
		if (epoll_event & (EPOLLIN | EPOLLOUT))
		{    
			if (getsockopt(fd, SOL_SOCKET, SO_ERROR, (char*)&err_ret, &len)<0 || err_ret != 0)
			{
				close(epoll_fd);
				epoll_fd = -1;
                LOG_ERROR("Connectepoll getsockopt  SO_ERROR  fd:%d",fd);
				return false;
			}
			//sucess
		}  
	} 

	close(epoll_fd);
	epoll_fd = -1;      
    
    LOG_ERROR("CheckConnect success");
    return true;
}
```

**Comment by caozhiyi** [comment]
这样恐怕不行，这个函数会阻塞太长时间，而cppnet所有函数调用都应该是异步非阻塞的。
新的修改里，判断socket是否连接，依然是
```
igetsockopt(fd, SOL_SOCKET, SO_ERROR, (char*)&err_ret, &len)
```
这个接口，按道理讲，可能会因为建连耗时长，而返回其他异常，不会返回成功。

新修改里最大的改动是延迟了上述接口的检查时机，可以通过修改配置定时器的时间来实现。
cppnet/cppnet_config.cpp中
```
static const uint16_t __connect_recheck_time_ms
```
