### ISSUE TITLE
如何优雅地实现一个同步读操作？

### ISSUE THREAD

**Issue by faywong** [caozhiyi/CppNet#40]
cppnet 的设计是：

```c++
    net.SetReadCallback(std::bind(&HttpServer::OnMessage, &server, std::placeholders::_1, std::placeholders::_2, ...)
```
异步回调的方式通知 caller 去读。我现在场景是一个同步一发一收的逻辑。如何优雅地实现同步读（若没有则等待）。

我现在构思的方法是把 ReadCallback 里收到的 buffer 汇聚并按照 handle 维度的 map 来存起来，然后在我 caller 读取的时候，实现一个读等待（若 buffer 没有或 buffer 内容为空）。包装这一层同步等就是有点绕。所以请教下有没有更好的解法。

**Comment by caozhiyi** [comment]
这倒是比较奇怪的需求，如果需要同步调用的话，为什么不用原始的socket语义呢？
如果要在cppnet的接口上实现同步阻塞的效果，你的方式确实有些复杂。需要维护中心式的数据存储来维护中间状态的数据，其次如果数据没有回来，也没有一个比较好的方式来等待，使用信号量的话，又会参杂一些线程逻辑，不妥。
感觉可以参考下无栈协程的实现方式，将你的发送和接收实现在一个函数里，然后把这个函数维护一个标识，来分成两段执行，以模拟顺序执行，这样的话，就是这个函数的签名得和cppnet的读取回调函数一致，对你代码有一定的入侵。
写个伪代码：
```
void syncWriteAndRead(const std::string& data, bool is_read, Handle handle, BufferPtr buf, uint32_t len) {
    if(!is_read) {
         // todo  发送逻辑
         return;
    }
    // todo 执行接收逻辑

}
```
在注册SetReadCallback的时候，通过占位符，把data绑定为空，is_read 绑定为 true
这个思路，你可以参考下。

此外，我觉得你的需求可能有点问题，同步调用的话，不要用异步库。

**Comment by caozhiyi** [comment]
这倒是比较奇怪的需求，如果需要同步调用的话，为什么不用原始的socket语义呢？
如果要在cppnet的接口上实现同步阻塞的效果，你的方式确实有些复杂。需要维护中心式的数据存储来维护中间状态的数据，其次如果数据没有回来，也没有一个比较好的方式来等待，使用信号量的话，又会参杂一些线程逻辑，不妥。
感觉可以参考下无栈协程的实现方式，将你的发送和接收实现在一个函数里，然后把这个函数维护一个标识，来分成两段执行，以模拟顺序执行，这样的话，就是这个函数的签名得和cppnet的读取回调函数一致，对你代码有一定的入侵。
写个伪代码：
```
void syncWriteAndRead(const std::string& data, bool is_read, Handle handle, BufferPtr buf, uint32_t len) {
    if(!is_read) {
         // todo  发送逻辑
         return;
    }
    // todo 执行接收逻辑

}
```
在注册SetReadCallback的时候，通过占位符，把data绑定为空，is_read 绑定为 true
这个思路，你可以参考下。

此外，我觉得你的需求可能有点问题，同步调用的话，不要用异步库。

**Comment by faywong** [comment]
是的。我昨天也思考了一下，本质上是我的领域需要一个同步写 & 读的 socket 接口，使用 CppNet 并不是最合适的。后边我转而去使用 sockpp（在 posix socket 上的简单封装）来实现了。不管怎样，非常感谢你的指点。
