### ISSUE TITLE
tcp 作为 client 一直连接 server，在 server 上已经显示连接成功，但是 cppnet没有会调上来

### ISSUE THREAD

**Issue by yflisa** [caozhiyi/CppNet#41]
cppnet 在 docker 中作为 socket 第三方的库使用，cppnet 中会作为 client 和其他应用的 server 连接，运行一段时间后，client 连接 server 一直不回调成功；在 server 上看 log 已经连接成功。附件中是 cppnet 的 log 
[Uploading cppnet_log.2024-12-20.log…]()
![image](https://github.com/user-attachments/assets/da4a225b-685c-45e2-b1dc-12d034186c24)

**Comment by caozhiyi** [comment]
抱歉，有些没理解你的使用场景。
你是用cppnet作为client和其他server通信，建立连接成功了但是cppnet没有回调通知吗？ 可否把你使用cppnet的场景代码贴一下
