### ISSUE TITLE
simple test error

### ISSUE THREAD

**Issue by MicePilot** [caozhiyi/CppNet#6]
1. 在嵌入式Linux上编译后，运行simple的测试，server启动后，client连接出现core了，Server端显示连接又断开了，gdb调试core的堆栈如下：
![image](https://user-images.githubusercontent.com/13869645/94504632-cff1fa00-023b-11eb-84dc-a3f1011ab442.png)

2. 请问有现成的http client类吗，还是说要自己改。

**Comment by caozhiyi** [comment]
1. 你这个奔溃的详细环境是多少？ 什么系统？什么版本好？ 我在Centos 7.0 和 Ubuntu 18.04上有没有复现。不好定位具体的原因。
2. 目前在test目录里https://github.com/caozhiyi/CppNet/tree/master/test/http 有个简单的测试http。目前倒是没有一个系统的http框架封装。

**Comment by MicePilot** [comment]
> 1. 你这个奔溃的详细环境是多少？ 什么系统？什么版本好？ 我在Centos 7.0 和 Ubuntu 18.04上有没有复现。不好定位具体的原因。
> 2. 目前在test目录里https://github.com/caozhiyi/CppNet/tree/master/test/http 有个简单的测试http。目前倒是没有一个系统的http框架封装。

崩溃时的环境是Raspberry Pi OS 1.4，另外我用Centos 7.6.1810也复现了该问题，难道是我编译的时候有什么问题吗，我库是运行build.sh编译的，test文件下各个示例的编译是直接make的

**Comment by caozhiyi** [comment]
抱歉，是之前我改版支持多个实例的时候留下的bug。已经修复掉啦。感谢提供此issue。
