### ISSUE TITLE
基于上次做的更新，我在windows端再次做了测试，发现simpleServer获取对端IP地址异常。

### ISSUE THREAD

**Issue by angryant198512** [caozhiyi/CppNet#9]
其他都正常了，唯独IP地址获取异常。
![image](https://user-images.githubusercontent.com/49151858/122713116-c1e77c00-d297-11eb-8edc-2371845d2d6d.png)

_Originally posted by @angryant198512 in https://github.com/caozhiyi/CppNet/issues/8#issuecomment-864747531_

**Comment by caozhiyi** [comment]
是因为在获取对端ip的时候，错误将IPv4地址按照IPv6转换了。
已经修复，感谢！

**Comment by angryant198512** [comment]
![image](https://user-images.githubusercontent.com/49151858/123041700-3f41f680-d428-11eb-9075-1053944907c0.png)
ubuntu16环境下编译测试，同样用simple测试，客户端无法连接到服务端。
